### ISSUE TITLE
Uncaught extra comma

### ISSUE THREAD

**Issue by rasensio1** [tcarlsen/atom-jsonlint#11]
Heyo!

Extra commas (if last attribute) are not caught. See example below:

![image](https://cloud.githubusercontent.com/assets/12215523/15709943/e2d9cf8e-2807-11e6-8a6d-b0341b4908df.png)

**Comment by tcarlsen** [comment]
this should be reported at the [jsonlint repo](https://github.com/zaach/jsonlint)

**Comment by rasensio1** [comment]
Got it. Thanks!
