### ISSUE TITLE
Feature Suggestion: Add "warning" check for duplicate keys

### ISSUE THREAD

**Issue by buren** [tcarlsen/atom-jsonlint#12]
Thanks for an awesome package 👍 

Just a feature suggestion :)

In a current project we have our translation strings in JSON-files and had a problem where we had defined the same key multiple times in the same JSON file.
Would be awesome to get a warning if that happens, something like `Warning: Duplicate keys found: key1, key2`.

**Comment by tcarlsen** [comment]
this should be requested at the linter project: https://github.com/zaach/jsonlint

I'm "just" wrapping his linter into atom 😄

**Comment by buren** [comment]
@tcarlsen thanks 👍 

I took a quick look in that repo and there are already to issues for it ;)

https://github.com/zaach/jsonlint/issues/85
https://github.com/zaach/jsonlint/issues/13
