### ISSUE TITLE
Multiple issues due to Atom pre1.0

### ISSUE THREAD

**Issue by pistou** [tcarlsen/atom-jsonlint#3]
Currently using Atom 0.190.0 on WIndows 8.1

**Workspace.eachEditor is deprecated**
Use Workspace::observeTextEditors instead

```
Workspace.eachEditor (c:\Users\Pierre\AppData\Local\atom\app-0.190.0\resources\app\src\workspace.js:942:7)
<unknown> (C:\Users\Pierre\.atom\packages\jsonlint\lib\main.coffee:14:23)
```

---

**Workspace.eachEditor is deprecated**
Use Workspace::observeTextEditors instead

```
Workspace.eachEditor (c:\Users\Pierre\AppData\Local\atom\app-0.190.0\resources\app\src\workspace.js:942:7)
<unknown> (C:\Users\Pierre\.atom\packages\jsonlint\lib\main.coffee:22:23)
```

---

**TextBuffer.on is deprecated**
Use TextBuffer::onDidStopChanging instead. If you need the modified status, call TextBuffer::isModified yourself in your callback.

```
TextBuffer.on (c:\Users\Pierre\AppData\Local\atom\app-0.190.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1161:16)
<unknown> (C:\Users\Pierre\.atom\packages\jsonlint\lib\main.coffee:23:24)
```

---

**TextBuffer.on is deprecated**
Use TextBuffer::onDidSave instead. A TextBuffer instance is no longer provided as a callback argument.

```
TextBuffer.on (c:\Users\Pierre\AppData\Local\atom\app-0.190.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1182:16)
<unknown> (C:\Users\Pierre\.atom\packages\jsonlint\lib\main.coffee:15:24)
```

**Comment by tcarlsen** [comment]
yeah im aware that I have to update a lot of stuff for 1.0 :ghost: 

Thanks for the sum up ! :+1:

**Comment by pistou** [comment]
:+1:
